[workspace]
members = ["packages/*"]
exclude = ["contracts"]

# Resolver has to be set explicitely in workspaces
# due to https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[workspace.package]
version = "2.1.3"

[workspace.dependencies]
schemars = "0.8.4"
serde = { version = "1.0.192", default-features = false, features = ["derive", "alloc"] }

[workspace.metadata.release]
shared-version = true
tag-message = "chore: Release cosmwasm v{{version}}"
tag-name = "v{{version}}"
