[package]
name = "cw-schema-codegen"
authors = ["Aumetra Weisman <aumetra@confio.gmbh>"]
edition = "2021"
version.workspace = true
publish = false

[dependencies]
anyhow = "1.0.89"
askama = { version = "0.12.1", default-features = false }
clap = { version = "4.5.18", features = ["derive"] }
cw-schema = { version = "=2.1.3", path = "../cw-schema" }
either = "1.13.0"
frunk = "0.4.3"
log = "0.4.22"
serde_json = "1.0.128"
simple_logger = "5.0.0"
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
