[package]
name = "cosmwasm-schema-derive"
version.workspace = true
authors = ["Tomasz Kurcz <tom@confio.gmbh>"]
edition = "2021"
description = "Derive macros for cosmwasm-schema"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
proc-macro2 = "1"
quote = "1"
strum = { version = "0.26.3", features = ["derive"] }
syn = { version = "2", features = ["extra-traits", "full", "printing"] }

[lib]
proc-macro = true
