[package]
name = "go-gen"
authors = ["Christoph Otter <chris@confio.gmbh>"]
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
schemars = "0.8.3"
cosmwasm-std = { path = "../std", version = "2.0.8", features = ["cosmwasm_2_0", "staking", "stargate"] }
cosmwasm-schema = { path = "../schema", version = "2.0.8" }
anyhow = "1"
Inflector = "0.11.4"
indenter = "0.3.3"
